version: '3.4'

services:
  desafio.web:
    image: ${DOCKER_REGISTRY-}desafioweb
    depends_on:
    - desafio.api
    - sqlserver
    ports:
    - "20000:80"
    networks:
    - desafio-network
    build:
      context: .
      dockerfile: Desafio.Web/Dockerfile

  desafio.api:
    image: ${DOCKER_REGISTRY-}desafioapi  
    depends_on:   
    - sqlserver
    ports:
    - "20001:80"
    networks:
    - desafio-network
    build:
     context: .
     dockerfile: Desafio.API/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - desafio-network
    environment:
      - SA_PASSWORD=Admin1q2w3e@
      - ACCEPT_EULA=Y
    ports:
      - "1451:1433"
 

networks:
  desafio-network:
    driver: bridge
      

